# Generated by Django 4.1.6 on 2023-02-18 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
